# Generated by Django 5.0.6 on 2024-07-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
